# Generated by Django 4.0.4 on 2022-07-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prize', models.IntegerField(max_length=30)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
            ],
        ),
    ]
